[package]
name = "rle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["cargo"] }
predicates = "2.1.5"

[dev-dependencies]
assert_cmd = "2"
